"on":
  push:
    branches:
    - master
name: Deploy to Porter
jobs:
  porter-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2.3.4
    - name: Download Porter
      id: download_porter
      run: |
        version=v0.6.1
        name=porter-$version.zip
        curl -L https://github.com/porter-dev/porter/releases/download/${version}/porter_${version}_Linux_x86_64.zip --output $name
        unzip -a $name
        rm $name
        chmod +x ./porter
        sudo mv ./porter /usr/local/bin/porter
    - name: Update Porter App
      id: update_porter
      timeout-minutes: 10
      run: porter update --host https://dashboard.dev.getporter.dev --token ${{ secrets.PORTER_TOKEN_3
        }} --project 3 --cluster 5 --app test-buildpack-gha
