"on":
  push:
    branches:
    - master
name: Deploy to Porter
jobs:
  porter-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2.3.4
    - name: Update Porter App
      timeout-minutes: 20
      uses: porter-dev/porter-update-action@add-tag
      with:
        app: exciting-exchange-cage
        cluster: "8"
        host: https://dashboard.dev.getporter.dev
        project: "10"
        token: ${{ secrets.PORTER_TOKEN_10 }}
