"on":
  push:
    branches:
    - master
name: Deploy to Porter
jobs:
  build_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4
      - name: Set Github tag
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Build image
        timeout-minutes: 10
        uses: porter-dev/porter-cli-action@v0.1.0
        with:
          command: update build --app test-gcr-again --tag ${{ steps.vars.outputs.sha_short }} --stream
        env:
          PORTER_CLUSTER: "162"
          PORTER_PROJECT: "273"
          PORTER_TOKEN: ${{ secrets.PORTER_TOKEN_273 }}
      - name: Push image
        timeout-minutes: 10
        uses: porter-dev/porter-cli-action@v0.1.0
        with:
          command: update push --app test-gcr-again --tag ${{ steps.vars.outputs.sha_short }} --stream
        env:
          PORTER_CLUSTER: "162"
          PORTER_PROJECT: "273"
          PORTER_TOKEN: ${{ secrets.PORTER_TOKEN_273 }}
  porter-deploy:
    runs-on: ubuntu-latest
    needs: build_push
    steps:
    - name: Checkout code
      uses: actions/checkout@v2.3.4
    - name: Set Github tag
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
    - name: Update Porter App
      timeout-minutes: 20
      uses: porter-dev/porter-update-action@v0.1.0
      with:
        app: test-gcr-again
        cluster: "162"
        host: https://dashboard.getporter.dev
        namespace: default
        project: "273"
        tag: ${{ steps.vars.outputs.sha_short }}
        token: ${{ secrets.PORTER_TOKEN_273 }}
