"on":
  push:
    branches:
    - protected
name: Deploy to Porter
jobs:
  porter-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4
      - name: Set Github tag
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Update the Porter application
        timeout-minutes: 20
        uses: porter-dev/porter-cli-action@3743befec920bb2d7f8a59a4a1c1ff6b3debe8a6
        with:
          command: update --app protected-branch-test --tag ${{ steps.vars.outputs.sha_short }} --dockerfile ./subpath/Dockerfile --stream
        env:
          PORTER_HOST: https://dashboard.getporter.dev
          PORTER_CLUSTER: 162
          PORTER_PROJECT: 273
          PORTER_TOKEN: ${{ secrets.PORTER_TOKEN_273 }}
